name: CI & Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -U .
    - name: Test with pytest
      run: |
        pytest --cov-report term --cov=my_module
    - uses: codecov/codecov-action@v1
      with:
        token: 37ff8773-cd54-4477-ad50-340acb80ee51  # Not required for public repos
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

